// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 insertVector() ", "[example]")
{
	const int SIZE = 10;
	int usernum, idx;
	vector<int> number(10);

	srand(time(0));
	makeVector(number);
	printVector(number);
	usernum = 15;
	for (int i = 0; i < number.size(); i++)
	{
		if (number[i] > usernum)
		{
			idx = i;
			break;
		}
	}
	insertVector(number, usernum);
	printVector(number);

	REQUIRE(number[idx] == usernum);
}
// tests for exercise 2
TEST_CASE("Ex2 deleteVector()", "[example]")
{
	const int SIZE = 30;
	int usernum, idx, result, size;
	int cnt1 = 0;
	int cnt2 = 0;
	vector<int> number(SIZE);
	vector<int>::iterator iter;

	srand(time(0));

	makeVector(number);
	printVector(number);
	usernum = 16;
	iter = number.begin();
	while (1)
	{
		iter = find(iter, number.end(), usernum);
		if (iter == number.end())
			break;
		iter += 1;
		cnt1 += 1;
	}
	size = number.size();
	result = deleteVector(number, usernum);
	printVector(number);

	if (cnt1 > 0)
	{
		REQUIRE(number.size() == size - 1);
	}
	iter = number.begin();
	while (1)
	{
		iter = find(iter, number.end(), usernum);
		if (iter == number.end())
			break;
		cout << "debug iter " << *iter << endl;
		cout << distance(number.begin() , iter);
		iter += 1;
		cnt2 += 1;
	}
	REQUIRE(cnt1-1 == cnt2);
}